package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"
)

func TestFavoritesLayoutBrowser(t *testing.T) {
	if os.Getenv("GNOTES_BROWSER_CHECK") != "1" {
		t.Skip("optional local Chromium check")
	}
	for _, width := range []int{320, 600, 1024} {
		t.Run(fmt.Sprint(width), func(t *testing.T) {
			recoveryFixture(t)
			mustRecoveryExec(t, "INSERT INTO notes(user_id,title,content,created_at,tags) VALUES(1,'Long note',?,?,?)", strings.Repeat("A long paragraph to scroll through.\n\n", 90), time.Now().UTC(), `["work","a-very-long-category-name-for-small-screens"]`)
			mustRecoveryExec(t, "INSERT INTO notes(user_id,title,content,created_at,tags,favorited,archived_at) VALUES(1,'Saved archive','Archived important text',?,?,1,?)", time.Now().UTC(), `["reading"]`, time.Now().UTC())
			mux := http.NewServeMux()
			registerDictionaryRoutes(mux)
			mux.HandleFunc("/api/auth/config", authConfigHandler)
			mux.HandleFunc("/api/auth/login", loginHandler)
			mux.HandleFunc("/api/auth/me", protect(meHandler, false))
			mux.HandleFunc("/api/draft", protect(getDraftHandler, false))
			mux.HandleFunc("/api/notes/page", protect(pagedListNotesHandler, false))
			mux.HandleFunc("/api/notes/search-page", protect(pagedSearchNotesHandler, false))
			mux.HandleFunc("/api/notes/trash-page", protect(pagedTrashNotesHandler, false))
			mux.HandleFunc("/api/notes/favorite", protect(favoriteNoteHandler, true))
			mux.HandleFunc("/api/notes/favorite-date", protect(favoriteDateNotesHandler, true))
			mux.HandleFunc("/api/notes/update", protect(updateNoteHandler, true))
			mux.HandleFunc("/api/notes/tags", protect(updateNoteTagsHandler, true))
			mux.HandleFunc("/api/notes/archive", protect(noteArchiveHandler, false))
			mux.HandleFunc("/api/notes/unarchive", protect(unarchiveNoteHandler, true))
			mux.HandleFunc("/api/tags", protect(tagsHandler, false))
			mux.Handle("/", http.FileServer(http.Dir("../../public")))
			server := httptest.NewServer(securityHeaders(mux))
			defer server.Close()
			browser := newRecoveryBrowser(t)
			browser.call("POST", "/goog/cdp/execute", map[string]any{"cmd": "Emulation.setDeviceMetricsOverride", "params": map[string]any{"width": width, "height": 800, "deviceScaleFactor": 1, "mobile": false}})
			browser.navigate(server.URL)
			browser.wait(`!document.getElementById('auth-screen').hidden`)
			browser.script(`document.getElementById('auth-username').value='rick';document.getElementById('auth-password').value='original password';document.getElementById('auth-form').requestSubmit();`)
			browser.wait(`!notesLoading && loadedNotes.size===1 && spellingReady`)
			browser.script(`const nav=document.getElementById('primary-navigation');const mobile=innerWidth<=560;if((getComputedStyle(nav).position==='fixed')!==mobile)throw new Error('Navigation breakpoint incorrect');if(mobile){if(nav.parentElement.id!=='app-shell'||Math.abs(nav.getBoundingClientRect().bottom-innerHeight)>1)throw new Error('Navigation is not at bottom');const buttons=[nav.querySelector('.view-toggle'),nav.querySelector('.search-toggle'),nav.querySelector('#favorites-quick-open'),nav.querySelector('#archived-quick-open'),nav.querySelector('.trash-toggle'),nav.querySelector('#account-control > summary')];if(buttons.some(b=>b.getBoundingClientRect().width<44||b.getBoundingClientRect().height<48))throw new Error('Navigation targets too small: '+JSON.stringify(buttons.map(b=>({id:b.id,w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height}))));if(buttons[5].getBoundingClientRect().right>innerWidth)throw new Error('Profile outside viewport');window.scrollTo(0,300);if(Math.abs(nav.getBoundingClientRect().bottom-innerHeight)>1)throw new Error('Navigation scrolls away');window.scrollTo(0,0);for(const panel of document.querySelectorAll('.info-panel,.archive-panel')){if(parseFloat(getComputedStyle(panel).maxHeight)>innerHeight-140)throw new Error('Panel can extend behind navigation');}const account=document.getElementById('account-control');account.open=true;const menu=account.querySelector('.account-menu').getBoundingClientRect();if(menu.top<0||menu.bottom>nav.getBoundingClientRect().top)throw new Error('Profile menu outside viewport');account.open=false;}else if(!nav.closest('.site-header'))throw new Error('Desktop navigation left header');`)
			browser.script(`window.longID=[...loadedNotes.keys()][0];document.getElementById('view-toggle').click();const menu=document.getElementById('view-menu');if(menu.scrollWidth>menu.clientWidth+1)throw new Error('Controls menu scrolls horizontally');closeViewMenu();const range=document.getElementById('note-max-height');range.value='240';range.dispatchEvent(new Event('input',{bubbles:true}));const body=document.querySelector('.note-content');if(body.clientHeight>241||body.scrollHeight<=body.clientHeight)throw new Error('Long note is not capped and scrollable');if(document.documentElement.scrollWidth>innerWidth)throw new Error('Page overflows');applyDensityMode(2);const iconSize=parseFloat(getComputedStyle(document.querySelector('.note-quick-actions .icon')).width);if(iconSize<17||iconSize>=20)throw new Error('Titles icons must be between the small and original sizes');const title=document.querySelector('.note-view > h2').getBoundingClientRect(),tags=document.querySelector('.note-tags').getBoundingClientRect();if(tags.top-title.bottom<8)throw new Error('Title and tags overlap at '+innerWidth+'px');if(innerWidth<=700){const tag=document.querySelector('[data-tag=\"a-very-long-category-name-for-small-screens\"]');if(tag.dataset.shortLabel!=='#a-very-lon…'||getComputedStyle(tag.querySelector('.note-tag-label')).display!=='none'||getComputedStyle(tag,'::after').content==='none')throw new Error('Mobile tag was not shortened');if(tag.dataset.tag!=='a-very-long-category-name-for-small-screens')throw new Error('Tag value was truncated');}else{const tag=document.querySelector('[data-tag=\"a-very-long-category-name-for-small-screens\"]');if(getComputedStyle(tag).whiteSpace==='nowrap')throw new Error('Desktop tag was shortened');}applyDensityMode(0);openNoteEditor(longID,false);`)
			browser.wait(`richEdit && document.querySelector('.is-editing .tiptap')`)
			// Real wheel input must scroll the editing surface, without moving the footer.
			browser.script(`window.scrollElement=document.querySelector('.is-editing .tiptap');scrollElement.scrollTop=0;scrollElement.focus();scrollElement.scrollTop=0;window.scrollBounds=scrollElement.getBoundingClientRect();`)
			coords := browser.script(`return {x:Math.round(scrollBounds.left+scrollBounds.width/2),y:Math.round(scrollBounds.top+scrollBounds.height/2)}`).(map[string]any)
			browser.call("POST", "/actions", map[string]any{"actions": []any{map[string]any{"type": "wheel", "id": "scroll-editor", "actions": []any{map[string]any{"type": "scroll", "x": coords["x"], "y": coords["y"], "deltaX": 0, "deltaY": 600, "duration": 200}}}}})
			browser.wait(`scrollElement.scrollTop>100`)
			if width == 320 {
				browser.call("POST", "/goog/cdp/execute", map[string]any{"cmd": "Emulation.setTouchEmulationEnabled", "params": map[string]any{"enabled": true}})
				browser.script(`scrollElement.scrollTop=0;`)
				x, y := coords["x"].(float64), coords["y"].(float64)
				browser.call("POST", "/actions", map[string]any{"actions": []any{map[string]any{"type": "pointer", "id": "touch-scroll", "parameters": map[string]any{"pointerType": "touch"}, "actions": []any{
					map[string]any{"type": "pointerMove", "x": x, "y": y + 80, "duration": 0}, map[string]any{"type": "pointerDown", "button": 0},
					map[string]any{"type": "pointerMove", "x": x, "y": y - 100, "duration": 250}, map[string]any{"type": "pointerUp", "button": 0},
				}}}})
				browser.wait(`scrollElement.scrollTop>30`)
			}

			browser.script(`updateNote(longID);`)
			browser.wait(`editingNoteId===null && pendingNoteEdits.size===0 && !notesLoading`)
			browser.script(`applyEditorMode(true);openNoteEditor(longID,false);window.scrollElement=document.getElementById('edit-content-'+longID);scrollElement.scrollTop=0;window.scrollBounds=scrollElement.getBoundingClientRect();if(scrollElement.scrollHeight<=scrollElement.clientHeight)throw new Error('Source editor cannot scroll');`)
			coords = browser.script(`return {x:Math.round(scrollBounds.left+scrollBounds.width/2),y:Math.round(scrollBounds.top+scrollBounds.height/2)}`).(map[string]any)
			browser.call("POST", "/actions", map[string]any{"actions": []any{map[string]any{"type": "wheel", "id": "scroll-source", "actions": []any{map[string]any{"type": "scroll", "x": coords["x"], "y": coords["y"], "deltaX": 0, "deltaY": 600, "duration": 200}}}}})
			browser.wait(`scrollElement.scrollTop>100`)
			browser.script(`updateNote(longID);applyEditorMode(false);`)
			browser.wait(`pendingNoteEdits.size===0 && !notesLoading`)
			browser.script(`toggleFavorite(longID);if(loadedNotes.has(longID))throw new Error('Favorite remains in main view');`)
			browser.wait(`pendingNoteActions.size===0 && !notesLoading && loadedNotes.size===0`)
			browser.script(`document.getElementById('favorites-quick-open').click();`)
			browser.wait(`favoritesMode && !notesLoading && loadedNotes.size===2 && document.getElementById('favorites-category').options.length>=3`)
			browser.script(`if(document.documentElement.scrollWidth>innerWidth)throw new Error('Favorites overflows');const banner=document.getElementById('favorites-mode-banner'),query=document.getElementById('favorites-query'),category=document.getElementById('favorites-category');if(banner.querySelector('label')||!category.getAttribute('aria-label'))throw new Error('Category should have only an accessible label');if(query.getBoundingClientRect().height>35||Math.abs(query.getBoundingClientRect().top-category.getBoundingClientRect().top)>1||banner.getBoundingClientRect().height>(innerWidth<=520?85:60))throw new Error('Favorites filters are not compact');const archived=[...loadedNotes.values()].find(n=>n.archived_at);window.archivedID=archived.id;const card=document.getElementById('note-'+archivedID);setNoteActionsOpen(card,true);if(getComputedStyle(card.querySelector('[aria-label=\"Edit note tags\"]')).display==='none')throw new Error('Archived categories unavailable');setNoteActionsOpen(card,false);openNoteEditor(archivedID,false);if(editingNoteId!==null)throw new Error('Archived favorite was editable');const select=document.getElementById('favorites-category');select.value='reading';select.dispatchEvent(new Event('change',{bubbles:true}));`)
			browser.wait(`!notesLoading && loadedNotes.size===1 && loadedNotes.has(archivedID)`)
			browser.script(`const select=document.getElementById('favorites-category');select.value='';select.dispatchEvent(new Event('change',{bubbles:true}));`)
			browser.wait(`!notesLoading && loadedNotes.size===2`)
			browser.script(`document.getElementById('favorites-query').value='Archived';document.getElementById('favorites-query').dispatchEvent(new Event('input',{bubbles:true}));`)
			browser.wait(`!notesLoading && loadedNotes.size===1 && loadedNotes.has(archivedID)`)
			browser.script(`window.originalFetch=fetch.bind(window);window.fetch=(url,options={})=>typeof url==='string'&&url.startsWith('/api/notes/favorite')?new Promise(resolve=>window.failFavorite=()=>resolve(new Response('',{status:503}))):originalFetch(url,options);toggleFavorite(archivedID);if(loadedNotes.has(archivedID))throw new Error('Remove favorite waits for server');`)
			browser.wait(`typeof failFavorite==='function'`)
			browser.script(`failFavorite();`)
			browser.wait(`pendingNoteActions.size===0 && !notesLoading && loadedNotes.has(archivedID) && document.getElementById('note-action-dialog').open`)
			browser.script(`document.getElementById('note-action-dialog').close();window.fetch=originalFetch;toggleFavorite(archivedID);`)
			browser.wait(`pendingNoteActions.size===0 && !notesLoading && loadedNotes.size===0`)
			ids := browser.script(`return {longID,archivedID}`).(map[string]any)
			browser.navigate(server.URL)
			browser.wait(`!notesLoading && loadedNotes.size===0`)
			browser.script(`document.getElementById('new-note-area-toggle').click();if(!document.getElementById('note-form').hidden)throw new Error('New note area stays visible');`)
			browser.script(fmt.Sprintf(`window.longID=%v;window.archivedID=%v;`, ids["longID"], ids["archivedID"]))
			browser.script(`document.getElementById('favorites-main-toggle').click();`)
			browser.wait(`!notesLoading && showFavoritesInMain && loadedNotes.has(longID)`)
			browser.navigate(server.URL)
			browser.wait(`!notesLoading && showFavoritesInMain && loadedNotes.size===1`)
			browser.script(`if(showNewNoteArea||!document.getElementById('note-form').hidden||document.getElementById('new-note-area-toggle').getAttribute('aria-pressed')!=='false')throw new Error('New note preference lost on reload');document.getElementById('new-note-area-toggle').click();if(document.getElementById('note-form').hidden)throw new Error('New note area cannot be restored');`)
			browser.script(fmt.Sprintf(`window.longID=%v;window.archivedID=%v;`, ids["longID"], ids["archivedID"]))
			browser.script(`document.getElementById('favorites-main-toggle').click();`)
			browser.wait(`!notesLoading && !showFavoritesInMain && loadedNotes.size===0`)
			browser.script(`toggleArchiveMode();`)
			browser.wait(`archiveMode && !notesLoading && loadedNotes.size===1`)
			browser.script(`toggleFavorite(archivedID);if(loadedNotes.has(archivedID))throw new Error('Favorite remains in Archive');`)
			browser.wait(`pendingNoteActions.size===0 && !notesLoading && loadedNotes.size===0`)
			browser.script(`document.getElementById('favorites-main-toggle').click();`)
			browser.wait(`!notesLoading && showFavoritesInMain && loadedNotes.has(archivedID)`)
			browser.script(`document.getElementById('favorites-main-toggle').click();`)
			browser.wait(`!notesLoading && !showFavoritesInMain && loadedNotes.size===0`)
			browser.script(`toggleFavoritesMode();`)
			browser.wait(`favoritesMode && !notesLoading && loadedNotes.size===2`)
			browser.script(`toggleFavorite(archivedID);`)
			browser.wait(`pendingNoteActions.size===0 && !notesLoading && loadedNotes.size===1`)
			browser.script(`toggleArchiveMode();`)
			browser.wait(`archiveMode && !notesLoading && loadedNotes.has(archivedID) && !loadedNotes.get(archivedID).favorited`)
			browser.script(`const favorite=document.querySelector('.date-section-favorite'),fold=favorite.previousElementSibling,remove=favorite.nextElementSibling;if(!fold.classList.contains('date-section-toggle')||!remove.classList.contains('archive-date-remove'))throw new Error('Date action order incorrect');if(favorite.getBoundingClientRect().left-fold.getBoundingClientRect().right<11||remove.getBoundingClientRect().left-favorite.getBoundingClientRect().right<11)throw new Error('Date actions too close');favorite.click();`)
			browser.wait(`pendingNoteActions.size===0 && !notesLoading && loadedNotes.size===0`)
			browser.script(`toggleFavoritesMode();`)
			browser.wait(`favoritesMode && !notesLoading && loadedNotes.size===2`)
			browser.script(`toggleFavorite(longID);`)
			browser.wait(`pendingNoteActions.size===0 && !notesLoading && loadedNotes.size===1`)
			browser.script(`toggleFavoritesMode();`)
			browser.wait(`!favoritesMode && !archiveMode && !notesLoading && loadedNotes.has(longID)`)
			browser.script(`document.querySelector('.date-section-favorite').click();`)
			browser.wait(`pendingNoteActions.size===0 && !notesLoading && loadedNotes.size===0`)
			browser.script(`if(document.getElementById('note-max-height').value!=='240')throw new Error('Note height preference did not persist');`)
		})
	}
}
